
     defTextBoxFocus=CheckoutAddress_CheckoutFirstNameInput,CheckoutAddress_CheckoutLastNameInput,CheckoutAddress_CheckoutCompanyInput,CheckoutAddress_CheckoutAddressInput,CheckoutAddress_CheckoutAddressDetailInput,CheckoutAddress_CheckoutZipCodeInput,CheckoutAddress_CheckoutCityInput,CheckoutAddress_CheckoutStateInput,CheckoutAddress_CheckoutEmailInput,CheckoutAddress_CheckoutPhoneInput,CheckoutAddress_CheckoutCountryCodeInput

     defBtnFocus=CheckoutAddress_CheckoutContinueButton

     seg2Focus=CheckoutAddress_OrderSummary_OrderSummaryItemList
