
     defBtnFocus=CheckoutShippingMethod_CheckoutShippingMethodContinueBtn,CheckoutShippingMethod_ContinueBtn,CheckoutShippingMethod_CancelBtn,CheckoutShippingMethod_YesBtn,CheckoutShippingMethod_NoBtn

     seg2Focus=CheckoutShippingMethod_OrderSummary_OrderSummaryItemList
