
     ButtonSkinActive=CopyShoppingCart_ProceedToCheckoutBtn,CopyShoppingCart_SignInBtn,CopyShoppingCart_ButtonRound

     defBtnFocus=CopyShoppingCart_RiteAidRewardsBtn

     defRichTextLink=CopyShoppingCart_SignInLabel_linkskin

     defTextBoxFocus=CopyShoppingCart_PromoteCodeInput

     seg2Focus=CopyShoppingCart_ProductListCarousel_ProductCarousel

     Copyseg04e93bcaf53d242=CopyShoppingCart_CartProductList_ProductList
