
     CopydefRichTextLink=Form1_ReviewersAmount_linkskin,Form1_ProductPrice_linkskin,Form1_Description_linkskin,Form1_FavoriteCheckText_linkskin,Form1_MoreInfoText_linkskin,Form1_HowToUseText_linkskin,Form1_IngredientsText_linkskin,Form1_SafetyText_linkskin,Form1_DimensionsText_linkskin,Form1_ReviewsText_linkskin

     CopyButtonSkinActive=Form1_FavoriteButton,Form1_AddButton,Form1_MoreInfo,Form1_HowToUse,Form1_Ingredients,Form1_Safety,Form1_Dimensions,Form1_Reviews

     Copyseg0d7c6292babf647=Form1_Segment0b857dcb40e0a4c
