
     CopyCopydefRichTextLink1=ProductDetails_ReviewersAmount_linkskin,ProductDetails_ProductPrice_linkskin,ProductDetails_Description_linkskin,ProductDetails_FavoriteCheckText_linkskin,ProductDetails_MoreInfoText_linkskin,ProductDetails_HowToUseText_linkskin,ProductDetails_IngredientsText_linkskin,ProductDetails_SafetyText_linkskin,ProductDetails_DimensionsText_linkskin,ProductDetails_ReviewsText_linkskin

     CopyCopyButtonSkinActive1=ProductDetails_AddButton,ProductDetails_MoreInfo,ProductDetails_HowToUse,ProductDetails_Ingredients,ProductDetails_Safety,ProductDetails_Dimensions,ProductDetails_Reviews

     CopyCopyseg5=ProductDetails_FrequentlyBoughtSegment
