
     ButtonSkinActive=ShoppingCart_ProceedToCheckoutBtn,ShoppingCart_SignInBtn,ShoppingCart_ButtonRound

     defBtnFocus=ShoppingCart_RiteAidRewardsBtn

     defRichTextLink=ShoppingCart_SignInLabel_linkskin

     defTextBoxFocus=ShoppingCart_PromoteCodeInput

     seg2Focus=ShoppingCart_ProductListCarousel_ProductCarousel

     Copyseg04e93bcaf53d242=ShoppingCart_CartProductList_ProductList
